# Generated by Django 6.0.4 on 2026-05-03 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='farmerprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='address',
            field=models.TextField(default='Unknown address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='full_name',
            field=models.CharField(default='Unknown Farmer', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='is_farmer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='farmers/profiles/'),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='village',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.CharField(blank=True, choices=[('Milk', 'Milk'), ('Butter', 'Butter'), ('Ghee', 'Ghee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Vegetables', 'Vegetables'), ('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Dairy', 'Dairy')], default='Vegetables', max_length=20),
            preserve_default=False,
        ),
    ]
