# Generated by Django 6.0.4 on 2026-05-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_order_updated_at_order_farmer_order_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerprofile',
            old_name='mobile_number',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
